# Generated by Django 3.1.4 on 2021-03-05 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='optimal_session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.session'),
        ),
    ]
