# Generated by Django 3.1.4 on 2021-03-06 16:02

import backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_auto_20210306_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='session_id',
            field=models.UUIDField(default=backend.models.generate_unique_session_code, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='user_id',
            field=models.CharField(default=backend.models.generate_unique_user_code, editable=False, max_length=8, primary_key=True, serialize=False),
        ),
    ]
