# Generated by Django 3.1.4 on 2021-03-07 11:16

import backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_auto_20210306_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='session_id',
            field=models.CharField(default=backend.models.generate_unique_session_code, editable=False, max_length=8, unique=True),
        ),
    ]
