# Generated by Django 3.1.4 on 2021-03-07 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_auto_20210307_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='optimal_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.session'),
        ),
    ]
